// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type DelegateTask struct {
	ID                   string
	IntentTxid           string
	IntentMessage        string
	IntentProof          string
	RecoveryRegistration string
	Fee                  int64
	DelegatorPublicKey   string
	ScheduledAt          int64
	Status               int64
	FailReason           sql.NullString
	CommitmentTxid       sql.NullString
}

type DelegateTaskInput struct {
	TaskID    string
	Outpoint  string
	ForfeitTx sql.NullString
}

type SubscribedScript struct {
	Script string
}

type Vhtlc struct {
	ID     string
	Script string
}
